<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Trades Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 20px;
        }
        h1 {
            font-size: 18px;
            margin-bottom: 5px;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .info {
            margin-bottom: 10px;
            font-size: 9px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #4F46E5;
            color: white;
            padding: 8px 4px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
        }
        td {
            padding: 6px 4px;
            border-bottom: 1px solid #ddd;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .profit-positive {
            color: #10B981;
            font-weight: bold;
        }
        .profit-negative {
            color: #EF4444;
            font-weight: bold;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Trading History Report</h1>
        <div class="info">
            <strong>User:</strong> {{ $user->name }} ({{ $user->email }})<br>
            <strong>Currency:</strong> {{ $displayCurrency }}<br>
            @if($startDate || $endDate)
                <strong>Date Range:</strong>
                {{ $startDate ? \Carbon\Carbon::parse($startDate)->format('M d, Y') : 'Beginning' }}
                to
                {{ $endDate ? \Carbon\Carbon::parse($endDate)->format('M d, Y') : 'Present' }}<br>
            @endif
            <strong>Generated:</strong> {{ $generatedAt }}<br>
            <strong>Total Trades:</strong> {{ $deals->count() }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date/Time</th>
                <th>Symbol</th>
                <th>Type</th>
                <th>Volume</th>
                <th>Price</th>
                <th>Profit</th>
                <th>Commission</th>
                <th>Swap</th>
                <th>Broker</th>
            </tr>
        </thead>
        <tbody>
            @forelse($deals as $deal)
                <tr>
                    <td>{{ $deal->time ? \Carbon\Carbon::parse($deal->time)->format('Y-m-d H:i') : 'N/A' }}</td>
                    <td><strong>{{ $deal->symbol ?? 'N/A' }}</strong></td>
                    <td>{{ $deal->type ?? 'N/A' }}</td>
                    <td>{{ number_format($deal->volume ?? 0, 2) }}</td>
                    <td>{{ number_format($deal->price ?? 0, 5) }}</td>
                    <td class="{{ ($deal->profit ?? 0) >= 0 ? 'profit-positive' : 'profit-negative' }}">
                        {{ $displayCurrency }} {{ number_format($deal->profit ?? 0, 2) }}
                    </td>
                    <td>{{ number_format($deal->commission ?? 0, 2) }}</td>
                    <td>{{ number_format($deal->swap ?? 0, 2) }}</td>
                    <td>{{ $deal->tradingAccount->broker_name ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px;">No trades found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by TradeVisor on {{ $generatedAt }}</p>
    </div>
</body>
</html>
